### ISSUE TITLE
Can add WinXP installation Support for G2FM

### ISSUE THREAD

**Issue by crasadure** [a1ive/grub2-filemanager#205]
hi a1live

I know winxp an old OS..but old PC's are still using WinXP OS..
I tried to install Winxp  **Map Method** and **Ventoy method** with G2FM
it is loading ISO file firstly but then it is crashing like bluescreen at last point... 
this is my captured video : https://vimeo.com/417602721

can you add this support for old PC users to grub2 file manager?

Thanks your project..your project is best for boot all file types..

**Comment by a1ive** [comment]
Actually, I don't know how to boot WinXP ISO and install it.
@steve6375 How does E2B boot WinXP.iso?

**Comment by a1ive** [comment]
@crasadure please try.

**Comment by steve6375** [comment]
XP is very old and Legacy only.
You will have to use grub4dos to boot from an XP ISO.
You have to create a floppy disk in memory with a driver on it (WinVBlock or Firadisk).
You also have to write some data to memory which I don't think grub2 can do.
Even then it will only install to systems which have an IDE disk controller.
To install to more modern systems with SATA\SCSI\RAID disk controllers you also need to add another floppy disk with the correct INF file and drivers (60MB).
This is all done for you by Easy2Boot.
Since Easy2Boot already exists and includes agFM as well as grub4dos + XP support. Why don't you simply use Easy2Boot?
@crasadure - have you ever used Easy2Boot or WinSetupFromUSB (which uses Easy2Boot code)? How many systems have you installed in this way?

**Comment by crasadure** [comment]
> @crasadure please try.

Hi a1live;

You had added WinXP support to G2FM..firstly,thanks for your support...
I tested to install WinXP from VirtualBox..this is my capture test video :) 
My Test Video: https://vimeo.com/417979735 

I think,everything is OK,now...
Can you add this support to Ventoy Branch system?

**Comment by steve6375** [comment]
Did you do a full install of XP?

**Comment by crasadure** [comment]
> XP is very old and Legacy only.
> You will have to use grub4dos to boot from an XP ISO.
> You have to create a floppy disk in memory with a driver on it (WinVBlock or Firadisk).
> You also have to write some data to memory which I don't think grub2 can do.
> Even then it will only install to systems which have an IDE disk controller.
> To install to more modern systems with SATA\SCSI\RAID disk controllers you also need to add another floppy disk in memory with the correct INF file and drivers (60MB).
> This is all done for you by Easy2Boot.
> Since Easy2Boot already exists and includes agFM as well as grub4dos + XP support. Why don't you simply use Easy2Boot?
> @crasadure - have you ever used Easy2Boot or WinSetupFromUSB (which uses Easy2Boot code)? How many systems have you installed in this way?

hi steve6375...

I know your system....I had translated your system to Turkish language and had sent you language file :) 

but our forum users can not use easy2boot...your system is to complex for them...
but ı had used your system at my flash drive..ı am following you...
[TNCTR](https://www.tnctr.com/) users can not prefer easy2boot..
they are preferring AIBOOT or Multiboot Toolkit e.g systems...

now our favorite project is G2FM ...it is perfect project..

**Comment by crasadure** [comment]
> Did you do a full install of XP?

yes..it is continue to install...
watch my capture video on virtual machine..
https://vimeo.com/417990442
