### ISSUE TITLE
Multiple strings are hard-coded in English

### ISSUE THREAD

**Issue by Matthaiks** [a1ive/grub2-filemanager#243]
These strings were translated at Crowdin long time ago but they are shown in English:

Multiple **Boot ISO** entries except **Boot ISO (Ventoy)**
**GRUB Console**

I haven't seen all the options so there may be more such hard-coded strings.

Polish language (100% complete), v7.3.1

**Comment by a1ive** [comment]
"Boot ISO (Ventoy)" menu has been removed since https://github.com/a1ive/grub2-filemanager/commit/3597af877d42cef48006272fd14d8c735a06b289
Other "Boot ISO" entries are translated.
![Screenshot_20200726_183507](https://user-images.githubusercontent.com/10670106/88477024-412cdc80-cf6f-11ea-9fc0-87be743a9c8f.png)
![Screenshot_20200726_183535](https://user-images.githubusercontent.com/10670106/88477027-438f3680-cf6f-11ea-809f-9cd16d7a0e17.png)

**Comment by Matthaiks** [comment]
OK. It looks like some issue with Easy2Boot. Booted latest grubfm.iso from the E2B pendrive: 
![421421521634](https://user-images.githubusercontent.com/3577122/88477472-88e83f80-cf40-11ea-890a-540c3602dba9.jpg)
