### ISSUE TITLE
F1 Hot Key

### ISSUE THREAD

**Issue by abdullah-erturk** [a1ive/grub2-filemanager#308]
I am compiling from the source files in Turkish language, but when I press the F1 shortkey, I encounter an error like the picture.

![error](https://user-images.githubusercontent.com/54866587/103312928-8ded7580-4a2f-11eb-8302-3dd42bf32b02.JPG)

**Comment by steve6375** [comment]
exit to the grub2 console and type
```
echo $theme
set pager=1
cat $theme
```
Then problem will be in your theme file.

**Comment by abdullah-erturk** [comment]
I'm compiling on the original theme

**Comment by steve6375** [comment]
Do you have a \boot\grubfm\config file on your test USB drive?

**Comment by abdullah-erturk** [comment]
No.

I use original with everything.

All I do is compile it in Turkish.

**Comment by steve6375** [comment]
Try compiling an English version.

**Comment by abdullah-erturk** [comment]
I am compiling Grub2FM with the Cygwin package on Windows.

Compiling smoothly

Png files in hwinfo folder in theme\slack folder do not open on Windows. 

Perhaps the cause of the error could be these png files.

![png_error](https://user-images.githubusercontent.com/54866587/103315687-5edb0200-4a37-11eb-8387-8fff602876c0.JPG)

**Comment by steve6375** [comment]
When I copied the source files to a Windows system from a linux VM I got some symbolic link errors.
Could this be the issue? It compiles OK under Linux and F1 works OK.

**Comment by abdullah-erturk** [comment]
Yes, it can be compiled under linux without any problem, but it is not always possible for me to use Linux.

I am stuck with the Windows operating system for my job

As I wrote in the previous post, the problem is most likely pgn files that cannot be previewed on Windows.

**Comment by steve6375** [comment]
Error when copying from Linux VM to shared Windows folder - possibly due to attributes?
![image](https://user-images.githubusercontent.com/1469350/103321649-92675d80-4a32-11eb-8a57-0f3224fd6ebb.png)
![image](https://user-images.githubusercontent.com/1469350/103321660-a14e1000-4a32-11eb-8c68-5c9b9493a4a6.png)
![image](https://user-images.githubusercontent.com/1469350/103321695-cfcbeb00-4a32-11eb-92f0-3427aa2a514d.png)
![image](https://user-images.githubusercontent.com/1469350/103321766-19b4d100-4a33-11eb-8f1c-7d285aff83fd.png)


![image](https://user-images.githubusercontent.com/1469350/103321535-06553600-4a32-11eb-861e-ed3b85175d08.png)
![image](https://user-images.githubusercontent.com/1469350/103321547-1240f800-4a32-11eb-8662-06e4b0312255.png)
![image](https://user-images.githubusercontent.com/1469350/103321553-1b31c980-4a32-11eb-97e1-e36870718422.png)
![image](https://user-images.githubusercontent.com/1469350/103321571-3270b700-4a32-11eb-854b-862edcc35532.png)
![image](https://user-images.githubusercontent.com/1469350/103321581-3ef50f80-4a32-11eb-94a9-09da14778c19.png)
![image](https://user-images.githubusercontent.com/1469350/103321586-4a483b00-4a32-11eb-9e86-38ca1f2a147d.png)
![image](https://user-images.githubusercontent.com/1469350/103321594-559b6680-4a32-11eb-999f-8f93b87f8e64.png)
etc.

**Comment by a1ive** [comment]
7-Zip does not support symbolic links.
You need to use git to get latest source code under linux or win10 wsl and build it.

**Comment by steve6375** [comment]
I did use git to get source code under Linux. I built OK using build script.
I am copying from the Linux Mint source folder in VBox 5 to a shared Windows folder on the host system and get errors. I am not using 7zip (I just use it to show attributes). Why do some files have many attributes, but most other files do not?

**Comment by a1ive** [comment]
I'm not sure if the ZIP format supports symbolic links. 
On your screenshot, the normal files are compressed, while symbolic links are not.
These are UNIX filesystem permissions, 'l' means 'symbolic link'.

**Comment by Tnctr-altay-24** [comment]
https://github.com/a1ive/grub2-filemanager/issues/308#issuecomment-752250858
https://github.com/a1ive/grub2-filemanager/issues/307#issuecomment-751971387

Yes, I was getting the same error from png in the theme file, then I changed the .png, system now it works fine.

**Comment by abdullah-erturk** [comment]
Master a1ive, can you replace png files in the hwinfo folder with their original files instead of Symbolic Link?

**Comment by steve6375** [comment]
What about the \boot\grubfm\types folder? That also has many linked files - do they all appear in your Windows folder (e.g. ima gif jpg jpeg etc.?

**Comment by abdullah-erturk** [comment]
There is no problem with the types folder.

The only problem is that the png files in the hwinfo folder cannot be opened on Windows.

It's not too difficult, just replace the png files in the hwinfo folder with the original files symbolically :)

**Comment by steve6375** [comment]
but the types folder contains many symlink files??? How can there be no problem with these?
[symlink.txt](https://github.com/a1ive/grub2-filemanager/files/5753809/symlink.txt)

**Comment by a1ive** [comment]
> There is no problem with the types folder.
> The only problem is that the png files in the hwinfo folder cannot be opened on Windows.

The types folder also has problems that you just didn't notice.
Files with exactly the same content do not need and should not be kept in multiple copies.

**Comment by steve6375** [comment]
Users who wish to make their own custom themes may need to copy the slack theme files into their own theme folders. Because some of the slack files are symlink'ed, this makes it hard for Windows users to create themes.

**Comment by a1ive** [comment]
I don't think copy and paste means "hard".

**Comment by steve6375** [comment]
How should a Windows user extract and make a copy of the current 'slack' theme?

**Comment by abdullah-erturk** [comment]
a1live thank you very much for the change 

it's super now...
